name: .NET CI

on: 
  push:
    branches: 
      - main

jobs: 
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build ConsoleApp1.sln 

      - name: Run tests
        run: dotnet test ConsoleApp1.sln 